// Decoded: the synthesize-speech edge function. Takes plain text plus a target
// language and returns natural-sounding speech as base64 MP3, generated by
// ElevenLabs. The API key lives in the function's environment
// (ELEVENLABS_API_KEY) and never reaches the browser.
//
// The browser's built-in voices vary by device and sound robotic; routing
// through ElevenLabs gives every listener the same premium, human-sounding
// voice. ElevenLabs' multilingual model auto-detects the language from the text
// (which is already written in the target language), so it speaks each language
// natively. If a language is unsupported or the key is missing, this returns an
// error and the client falls back to the on-device voice.
//
// Runs on the InsForge Deno runtime.

const corsHeaders: Record<string, string> = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization",
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

// Languages we offer that the ElevenLabs multilingual model handles well.
// Anything outside this set (e.g. Haitian Creole) falls back to the browser.
const SUPPORTED = new Set(["en", "es", "zh", "vi", "fr", "ar"]);

// Voice from the ElevenLabs voice library. Override per deployment with the
// ELEVENLABS_VOICE_ID env var (any voice id from your ElevenLabs voice library).
const DEFAULT_VOICE = "Gfpl8Yo74Is0W6cPUWWT";

interface SpeakBody {
  text?: string;
  language?: string; // short BCP-47, e.g. "en", "es"
}

function toBase64(buf: ArrayBuffer): string {
  const bytes = new Uint8Array(buf);
  let binary = "";
  const step = 0x8000; // chunk to avoid arg-count limits on String.fromCharCode
  for (let i = 0; i < bytes.length; i += step) {
    binary += String.fromCharCode(...bytes.subarray(i, i + step));
  }
  return btoa(binary);
}

async function synthesize(text: string): Promise<string | null> {
  const key = Deno.env.get("ELEVENLABS_API_KEY");
  if (!key) throw new Error("ELEVENLABS_API_KEY is not set on the function");

  const voiceId = Deno.env.get("ELEVENLABS_VOICE_ID") || DEFAULT_VOICE;
  // Multilingual v2 is the broad, high-quality model; override with
  // ELEVENLABS_MODEL_ID (e.g. eleven_turbo_v2_5) if you prefer cheaper/faster.
  const modelId = Deno.env.get("ELEVENLABS_MODEL_ID") || "eleven_multilingual_v2";

  const res = await fetch(
    `https://api.elevenlabs.io/v1/text-to-speech/${voiceId}?output_format=mp3_44100_128`,
    {
      method: "POST",
      headers: { "xi-api-key": key, "Content-Type": "application/json", Accept: "audio/mpeg" },
      body: JSON.stringify({
        text,
        model_id: modelId,
        voice_settings: { stability: 0.5, similarity_boost: 0.75 },
      }),
    },
  );
  if (!res.ok) return null;
  const buf = await res.arrayBuffer();
  return buf.byteLength ? toBase64(buf) : null;
}

export default async function handler(req: Request): Promise<Response> {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  if (req.method !== "POST") return json({ ok: false, error: "POST only" }, 405);
  try {
    const body = (await req.json()) as SpeakBody;
    const text = (body.text || "").trim().slice(0, 4800); // keep requests modest
    if (!text) return json({ ok: false, error: "Provide text" }, 400);

    const short = (body.language || "en").toLowerCase().split("-")[0];
    if (!SUPPORTED.has(short)) {
      return json({ ok: false, error: `Language ${short} not supported by cloud voice` }, 422);
    }

    const audio = await synthesize(text);
    if (!audio) return json({ ok: false, error: "Synthesis failed" }, 502);

    return json({ ok: true, audio, mime: "audio/mpeg" });
  } catch (e) {
    return json({ ok: false, error: String((e as Error)?.message ?? e) }, 500);
  }
}
